---
- name: download ros release
  get_url:
    url: "https://github.com/ros2/ros2/releases/download/release-{{ ros2_release }}/ros2-{{ ros2_release }}.tar.bz2"
    dest: "{{ ros2_download_dest }}"
- name: extract ros release
  unarchive:
    dest: "/tmp"
    src: "{{ ros2_download_dest }}"
    remote_src: yes
    creates: "{{ ros2_install_location }}"
    mode: "755"
  notify: correct ros2 install directory
- name: flush handlers
  meta: flush_handlers
