---
- name: download ros release
  get_url:
    url: "https://github.com/ros2/ros2/releases/download/release-{{ ros2_release }}/ros2-{{ ros2_release }}-linux-{{ ansible_distribution_release }}-amd64.tar.bz2"
    dest: "{{ ros2_download_dest }}"
- name: extract ros release
  unarchive:
    dest: "{{ ros2_install_location | dirname }}"
    src: "{{ ros2_download_dest }}"
    remote_src: yes
    creates: "{{ ros2_install_location }}"
    mode: "755"
  notify: correct ros2 install directory
- name: flush handlers
  meta: flush_handlers
- name: add ros env to shell
  when: ros2_shell_startup
  lineinfile:
    path: "~/.profile"
    line: "source {{ ros2_install_location }}/ros2-linux/setup.sh"
    state: present
