---
- name: install needed packages
  become: yes
  apt:
    name:
      - build-essential
      - software-properties-common
      - curl
      - gnupg
      - lsb-release
      - libpython3-dev
      - python3-pip
    state: present
    update_cache: yes
    install_recommends: yes
# Taken from https://github.com/ansible/ansible/issues/48714
- name: Enable universe repository
  become: yes
  when: ros2_enable_universe
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"
- name: get ros repo key
  become: yes
  apt_key:
    url: "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
    state: present
- name: enable ros repo
  become: yes
  apt_repository:
    repo: "deb {{ ros2_apt_repo }} {{ ansible_distribution_release }} main"
    state: present
- name: install rosdep
  become: yes
  apt:
    name: python3-rosdep
    install_recommends: yes
    state: present
- name: create install location
  file:
    path: "{{ ros2_install_location }}"
    state: directory
    mode: "0755"
