---
- name: rosdep init
  become: yes
  when: rosdep_init_update == true
  shell:
    cmd: rosdep init
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
- name: rosdep update
  when: rosdep_init_update
  shell:
    cmd: rosdep update
- name: install dependencies
  when: rosdep_install
  shell:
    cmd: "rosdep install --from-paths {{ ros2_install_location }}/ros2-linux/share --ignore-src -y --skip-keys '{{ rosdep_packages | join(' ') }}'"
