- name: mv ros2 install directory
  copy:
    src: "/tmp/ros2-linux"
    dest: "{{ ros2_install_location }}"
    mode: "0755"
    remote_src: yes
  listen: correct ros2 install directory
- name: remove temp ros2 extracted directory
  file:
    path: "/tmp"
    state: absent
  listen: correct ros2 install directory
